### ISSUE TITLE
`wasm-pack` vs `wasm-pack.cmd`

### ISSUE THREAD

**Issue by KamWithK** [wasm-tool/rollup-plugin-rust#22]
Right here in the code manually switches to using `wasm-pack.cmd` on Windows instead of `wasm-pack`:
https://github.com/wasm-tool/rollup-plugin-rust/blob/master/index.js#L154

I'm having some trouble with this on my Windows machine. `wasm-pack` by itself seems to work/run fine but when I try `wasm-pack.cmd` this isn't found. I got this to work locally by modifying the line into:
```javascript
const command = "wasm-pack";
```

If this works on some Windows systems but not others would it potentially be better to try [line 160](https://github.com/wasm-tool/rollup-plugin-rust/blob/master/index.js#L160) with `wasm-pack` and if it fails catch the exception and retry with `wasm-pack.cmd`? Would this be a potentially better solution (the code refers to the current one as hacky itself)?
Happy to fork and create a PR for this if it's something that could help others out :)

**Comment by Pauan** [comment]
There is currently a regression which causes wasm-pack to break completely on Windows: https://github.com/rustwasm/wasm-pack/issues/1038

Most likely you are running into that. What error message do you get when you use rollup-plugin-rust?

**Comment by KamWithK** [comment]
Yeah I was getting `You must install wasm-pack before you can run it` but after I changed the command variable to reference `wasm-pack` everything compiles and runs fine. I should probably mention that I manually ran the installer for wasm-pack beforehand.

**Comment by Pauan** [comment]
@KamWithK Okay, then it's the same bug. The reason why changing it to `wasm-pack` worked is because you have wasm-pack installed separately, so it's now using your separate wasm-pack. But that won't work for a fresh installation, so the bug in wasm-pack needs to be fixed.

**Comment by KamWithK** [comment]
Ahh okay that makes sense, thanks for helping @Pauan!

**Comment by MendyBerger** [comment]
Had the same issue with a fresh install of wasm-pack, going into the `@wasm-tool/rollup-plugin-rust` source code and changing the `command` variable to `wasm-pack` resolved the issue for me as well

**Comment by Pauan** [comment]
@MendyBerger This shouldn't be an issue anymore, unless it regressed. Are you using Windows? Did you install wasm-pack separately (you shouldn't)?

**Comment by MendyBerger** [comment]
I'm on Windows.
Created a new project, ran rollup, and got the following error:
```
You must install wasm-pack.exe before you can run it
``` 

So I installed `wasm-pack` manually but still got the error, but after changing `command` to `"wasm-pack"` it compiled successfully

**Comment by Pauan** [comment]
@MendyBerger You shouldn't install wasm-pack manually, it will cause problems. What version of rollup-plugin-rust are you using?

**Comment by MendyBerger** [comment]
Not on that computer now, will check as soon as I can

**Comment by MendyBerger** [comment]
`@wasm-tool/rollup-plugin-rust` `1.0.7`

But this doesn't seem to be the problem, because uninstalling and reinstalling all npm packages resolves the issue. Rather, it looks like the problem is in `create-tauri-app` with the `Dominator` recipe, I was able to recreate this issue and resolve it the same way, actually looks a bit like https://github.com/tauri-apps/tauri/pull/1912#issuecomment-883358610

**Comment by Pauan** [comment]
@MendyBerger The issue should have been fixed with the latest version of wasm-pack. And the fact that it works after you reinstalled all npm packages means that you probably just had an older version of wasm-pack installed.

Do you still get the same problem with a completely fresh installation of Tauri?

**Comment by MendyBerger** [comment]
Really sorry for the late response, I'm incredibly busy lately.

Not sure what I'd reinstall, I just run `npx create-tauri-app`

**Comment by Pauan** [comment]
@MendyBerger Yes, could you try creating a fresh project with `npx create-tauri-app`? [When you use `npx` it will always use the latest version of the package.](https://www.hacksparrow.com/nodejs/what-is-npx.html#use-and-discard-commands)

**Comment by MendyBerger** [comment]
@Pauan If that's the case then yes, I'm able to recreate the issue
