### ISSUE TITLE
Error when bundling generated functions

### ISSUE THREAD

**Issue by urschrei** [wasm-tool/rollup-plugin-rust#3]
I'm using the plugin to generate an ES module like so:

```
import rust from "@wasm-tool/rollup-plugin-rust";

export default {
    input: {
        example: "Cargo.toml",
    },
    output: {
        dir: "dist/js",
        format: "es",
        sourcemap: true,
    },
    plugins: [
        rust({
            serverPath: "static/js/",
        }),
    ],
};
```

And I then copy it, and import it in my `script.js`:

```
import {
    foo_func,
} from './js/example.js'
```

But when I run rollup to bundle `script.js`, I get the following errors:

```
/Users/sth/dev/wasmt/static/js/example.js
  56:17  error  Parsing error: Unexpected token import

✖ 1 problem (1 error, 0 warnings)

[!] Error: 'foo_func' is not exported by static/js/example.js, imported by static/script.js
```

I'm fairly certain that the error isn't on the Rust side; I've annotated my functions:

```
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub fn foo_func(words: &str) -> Coordinates {
    // body here
}
```

And I can run e.g. `wasm-pack build --target bundle` and `cargo +nightly build --release --target wasm32-unknown-unknown`, and they execute correctly, so I'm not sure what's going on…

**Comment by Pauan** [comment]
@urschrei I don't see any JS code in your bundle, how are you loading `script.js`?

**Comment by urschrei** [comment]
Oh, sorry. I'm loading it from an `index.html` using `<script src="static/js/script.js"></script>`

The full contents of `script.js` are

```
import {
    foo_func,
} from './js/example.js'

console.log(foo_func("hello there"));
```

**Comment by urschrei** [comment]
At least one error source is in the `init` function in `example.js` generated by the plugin when you specify `es` as the output type:

from `example.js`:

```
async function init(input) {
    if (typeof input === 'undefined') {
        input = import.meta.url.replace(/\.js$/, '_bg.wasm');
    }
    const imports = {};
    imports.wbg = {};
    imports.wbg.__wbindgen_throw = function(arg0, arg1) {
        throw new Error(getStringFromWasm0(arg0, arg1));
    };

    if (typeof input === 'string' || (typeof Request === 'function' && input instanceof Request) || (typeof URL === 'function' && input instanceof URL)) {
        input = fetch(input);
    }

    const { instance, module } = await load(await input, imports);

    wasm = instance.exports;
    init.__wbindgen_wasm_module = module;

    return wasm;
}
```

`eslint` complains about `unexpected token: import` on the line

    input = import.meta.url.replace(/\.js$/, '_bg.wasm');

full `example.js`: https://gist.github.com/urschrei/007b461427d7592648f75f225947620e

**Comment by Pauan** [comment]
@urschrei Okay, that's your problem: you can't use `import` inside of scripts (it has to be inside of ES6 modules).

There's various ways to fix this, but in your case the best way is to use Rollup to bundle the `script.js` file and change it to use `format: "iife"`:

```js
// script.js
import wasm from "./Cargo.toml";

async function run() {
    const exports = await wasm();
    console.log(exports.foo_func("hello there"));
}

run().catch(console.error);
```

```js
// rollup.config.js
import rust from "@wasm-tool/rollup-plugin-rust";

export default {
    input: {
        script: "./script.js",
    },
    output: {
        dir: "dist/js",
        format: "iife",
        sourcemap: true,
    },
    plugins: [
        rust({
            serverPath: "static/js/",
        }),
    ],
};
```

**Comment by urschrei** [comment]
Ah, this is progress: I can execute the generated `script.js` and it's working. So is there a way I can specify the exports outside of `async function run() {}` so I can create a deployable ES module that I can use with Webpack _and_ Rollup, or is that not the intention? (sorry, I'm only an occasional JS person)

**Comment by Pauan** [comment]
Browsers require Wasm to be async, so you have to export an `async` function.

Webpack allows you to write code which *looks* synchronous, but Webpack actually transforms it into async code (because of the requirement that Wasm must be async).

This sort of "cheating" is only done by Webpack, not other bundlers. So the only way to make your code work in all bundlers is to export an `async` API.

**Comment by urschrei** [comment]
OK, that explains it. Thanks!
