### ISSUE TITLE
bug: cmd vs exe on Windows 

### ISSUE THREAD

**Issue by DougAnderson444** [wasm-tool/rollup-plugin-rust#30]
https://github.com/wasm-tool/rollup-plugin-rust/blob/98c84e9483d4fb4e03bbb2ace49e3772b9ccd6e5/index.js#L145

Every time I need this to work on windows, I end up changing this from `.cmd` to `.exe`

Is there something that I'm missing?

**Comment by IcyTv** [comment]
Quick hack is to add a `wasm-pack.cmd` to your path with
```batch
@echo off
wasm-pack %*
```

**Comment by Pauan** [comment]
I've removed wasm-pack in version 2.0.0, so this problem should be fixed now.
