### ISSUE TITLE
Custom wasm-pack build command

### ISSUE THREAD

**Issue by aminya** [wasm-tool/rollup-plugin-rust#5]
I want to use the following wasm-pack for building my rust program:
```json
"wasm": "wasm-pack build --target bundler",
```
or 
`--target nodejs`

Is this possible using rollup-plugin-rust?

In the [wasm-pack plugin](https://github.com/wasm-tool/wasm-pack-plugin), I can do this using extraArgs:
```js
extraArgs: "--target bundler --mode normal",
```

**Comment by Pauan** [comment]
This plugin calls `wasm-pack` for you, so you cannot call `wasm-pack` yourself.

Instead, just use `"wasm": "rollup --config"` and create a `rollup.config.js` file which [includes the plugin](https://github.com/wasm-tool/rollup-plugin-rust#usage). It will handle everything for you.

**Comment by aminya** [comment]
@Pauan The default options don't suit my use case. See this comment: https://github.com/wasm-tool/rollup-plugin-rust/pull/6#issuecomment-665735271

**Comment by Pauan** [comment]
Since the underlying issue with Node has been fixed, I'm going to close this.
